### PR TITLE
fixed some clippy warnings

### PR DESCRIPTION
**Pull request by llogiq**
Mostly readability nits, so should be fairly easy to review.

### CODE REVIEW

**Comment by vitiral** [comment]
"some" clippy warnings, lol. Wow I am new to this language.

Was this an automated tool which did this? It's awesome! I need to get this added to travis (speaking of which, where is travis... it should be working by now).

Thanks for the PR

**Comment by vitiral** [comment]
how did you do this without adding clippy to the Cargo dependencies like it says to do in [the guide](https://github.com/Manishearth/rust-clippy)?

**Comment by llogiq** [comment]
`cargo clippy`  works  if you have a nightly Rust and `cargo install clippy`.

**Comment by llogiq** [comment]
Btw. ping me if you need help with Travis.

**Comment by vitiral** [comment]
cool, I've got everything set up. Some questions though:
- how do I get the "help" for clippy? `cargo clippy -h` gives me the rustc help!
- how do I get clippy to fix things automatically?
- how do I get clippy to error if there are lint errors (for the build test)?

Thanks!

**Comment by llogiq** [comment]
* There is no help, alas – clippy works as a rustc plugin, and there is no interface to inject help test. The site has all the documentation, though
* clippy doesn't fix anything by itself. To do this reliably is quite hard. I hear killercup has a rustfix tool in early development that should be able to apply suggestions from lints, and the IntelliJ-Rust plugin also has made advances on that front.

You're welcome.

**Comment by vitiral** [comment]
Wait, so you did all of those by hand? Thanks a ton!

**Pull request merged**
